version: '3.8'
services:

  app:
    container_name: starter-kit-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:16.0-alpine3.18
    container_name: ${TYPEORM_DATABASE}
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    container_name: starter-kit-nginx
    build:
      context: ./config/nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
