version: '3.8'
services:
  db:
    image: postgres:14.0-alpine
    container_name: starter-kit-db
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    env_file:
      - .env
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    ports:
      - '8000:8000'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
